version: '2'
services:

  babeldb:
    extends:
      file: ./babel/docker-compose.yml
      service: babeldb

  babel:
    extends:
      file: ./babel/docker-compose.yml
      service: babel
    external_links:
      - babeldb:babeldb

  babelindex:
    extends:
      file: ./engine/docker-compose.yml
      service: babelindex

  engine:
    extends:
      file: ./engine/docker-compose.yml
      service: engine
    external_links:
      - babelindex:babelindex

  cover:
    build: ./cover
    external_links:
      - engine:engine
      - babel:babel
    environment:
      - BB_ENGINE_HOST=engine
      - BB_ENGINE_PORT=3002
      - BB_BABEL_HOST=babel
      - BB_BABEL_PORT=3000